name: SellAll
main: AndreasHGK\SellAll\SellAll
version: 1.3.1
api: 3.0.0
load: POSTWORLD
author: AndreasHGK
description: Sell all items in your hand or all items in your inventory with the same type as in your hand
depend: ["EconomyAPI"]
commands:
 sell:
  description: "Sell command"
  usage: "/sell all|hand|inventory"
  permission: sell.command
permissions:
 sell.command:
  default: op
 sell.hand:
  default: op
 sell.all:
  default: op
 sell.inv:
  default: op
 sell.reload:
  default: op